apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: helloworld
spec:
  template:
    spec:
      containers:
      - name: hello-world
        args: ["java", "-jar", "project/hello-world-1.0.0-jar-with-dependencies.jar", "test"]
