apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener
spec:
  serviceAccountName: pipelines # replace with OpenShift one
  triggers:
    - name: dev-trigger
      interceptors:
        - cel:
            filter: "header.match('X-GitHub-Event','push') && body.branch == 'master'" # update with correct values
      bindings:
        - name: git-binding
      template:
        name: pipeline-template