apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: gitrevision
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: run-deploy-pipeline-
        namespace: monitoring
      spec:
        serviceAccountName: pipelines
        pipelineRef:
          name: pipeline-deploy
        resources:
          - name: git-source
            resourceSpec:
              type: git
              params:
              - name: revision
                value: $(params.gitrevision)
