apiVersion: v1
kind: Secret
metadata:
  name: git-authentication
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  password: <Replace with your personal access token>
  username: pipeline
