apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-resource
  labels:
    app: hello-world
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/Cottonglow/cd-with-tekton-and-kustomize.git
